apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {RedisClusterName-claim}
  namespace: {RedisClusterNamespace}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      type: redis-cluster-storage
  volumeName: redis-cluster-pv
